version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  npm-publisher: uraway/npm-publisher@0.2.0

variables:
  - &node-build-image
    - image: circleci/node:12.16.1-stretch
  - &tag-soql-model /^soql-model-v(\d)+(\.(\d)+)+$/
  - &package-soql-model 'packages/soql-model'
  - &tag-soql-builder-ui /^soql-builder-ui-v(\d)+(\.(\d)+)+$/
  - &package-soql-builder-ui 'packages/soql-builder-ui'
  - &tag-soql-data-view /^soql-data-view-v(\d)+(\.(\d)+)+$/
  - &package-soql-data-view 'packages/soql-data-view'
  - &tag-language-server /^language-server-v(\d)+(\.(\d)+)+$/
  - &package-language-server 'packages/language-server'

commands:
  checkout-install-build:
    description: 'Runs the standard checkout, cache, install, and build commands'
    parameters:
      package-name:
        type: string
        default: ''
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Packages
          command: |
            echo 'Build all packages for linked dependencies'
            yarn run build

jobs:
  soql-builder-ui:
    docker: *node-build-image
    environment:
      PACKAGE_PATH: *package-soql-builder-ui
    steps:
      - checkout-install-build:
          package-name: "Soql Builder UI"
      - run:
          name: Run SOQL builder UI Unit Tests
          command: |
            echo 'Run SOQL builder UI Unit Tests'
            cd $PACKAGE_PATH
            yarn run test:unit:coverage
      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash) -F soql-builder-ui -t ${CODECOV_TOKEN}
      - persist_to_workspace:
          root: .
          paths:
            - *package-soql-builder-ui
            - Dependencies

  language-server:
    docker: *node-build-image
    environment:
      PACKAGE_PATH: *package-language-server
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Packages
          command: |
            echo 'Build all packages for linked dependencies'
            yarn run build
      - run:
          name: 'Language Server: Run LWC Unit Tests'
          command: |
            echo 'Language Server: Run LWC Unit Tests'
            cd $PACKAGE_PATH
            yarn run test:unit:coverage
      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash) -F language-server -t ${CODECOV_TOKEN}
      - persist_to_workspace:
          root: .
          paths:
            - *package-language-server
            - Dependencies

  soql-model:
    docker: *node-build-image
    environment:
      PACKAGE_PATH: *package-soql-model
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Packages
          command: |
            echo 'Build all packages for linked dependencies'
            yarn run build
      - run:
          name: 'Run SOQL Model Server Unit Tests'
          command: |
            echo 'Run SOQL Model Server Unit Tests'
            cd $PACKAGE_PATH
            yarn run test:unit:coverage
      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash) -F soql-model -t ${CODECOV_TOKEN}
      - persist_to_workspace:
          root: .
          paths:
            - *package-soql-model
            - Dependencies

  soql-data-view:
    docker: *node-build-image
    environment:
      PACKAGE_PATH: *package-soql-data-view
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - *package-soql-data-view
            - Dependencies

  notify-slack-build:
    docker: *node-build-image
    steps:
      - slack/notify:
          channel: web-tools-bot
          title: "Success: ${CIRCLE_USERNAME}'s commit-workflow"
          title_link: 'https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}'
          color: '#9bcd9b'
          message: "${CIRCLE_USERNAME}'s workflow <https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}|commit-workflow> in ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}\n(${CIRCLE_BRANCH})"
          include_project_field: false
          include_visit_job_action: false
          include_job_number_field: false

  publish-to-npm:
    docker: *node-build-image
    parameters:
      package:
        description: "The path to the package to publish from the monorepo"
        default: ""
        type: string
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Publishing To Npm'
          command: |
            echo <<parameters.package>>
      - npm-publisher/publish-from-package-version:
          package-path: << parameters.package >>
          publish-token-variable: NPM_TOKEN
          args:
            --access public
      - slack/notify:
          channel: web-tools-bot
          title: "Published: ${CIRCLE_USERNAME}'s published ${CIRCLE_TAG} to npm"
          title_link: 'https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}'
          color: '#9bcd9b'
          message: "${CIRCLE_USERNAME}'s workflow <https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}|commit-workflow> in ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}\n(${CIRCLE_TAG})"
          include_project_field: false
          include_visit_job_action: false
          include_job_number_field: false

workflows:
  version: 2
  commit-workflow:
    jobs:
      # ---- runs on all branches and tag: soql-builder-ui-vX.X.X ----
      - soql-builder-ui:
          filters:
            tags:
              only: *tag-soql-builder-ui
      # ---- runs on all branches and tag: language-server-vX.X.X ----
      - language-server:
          filters:
            tags:
              only: *tag-language-server
      # ---- runs on all branches and tag: soql-model-vX.X.X ----
      - soql-model:
          filters:
            tags:
              only: *tag-soql-model
      # ---- runs on all branches and tag: soql-model-vX.X.X ----
      - soql-data-view:
          filters:
            tags:
              only: *tag-soql-data-view
      - notify-slack-build:
          # REMOVE BEFORE MERGE
          filters:
            branches:
              ignore: /.*/
          requires:
            - soql-builder-ui
            - language-server
            - soql-model
      # ---- Publish Soql Model - runs on tag: soql-model-vX.X.X ----
      - publish-to-npm:
          name: 'Publish Soql Model'
          package:
            *package-soql-model
          filters:
            branches:
              ignore: /.*/
            tags:
              only: *tag-soql-model
          requires:
            - soql-model
      # ---- Publish Soql Builder UI - runs on tag: soql-builder-ui-vX.X.X ----
      - publish-to-npm:
          name: 'Publish Soql Builder UI'
          package:
            *package-soql-builder-ui
          filters:
            branches:
              ignore: /.*/
            tags:
              only: *tag-soql-builder-ui
          requires:
            - soql-builder-ui
      # Publish Language Server - runs on tag: language-server-vX.X.X ----
      - publish-to-npm:
          name: 'Publish Language Server'
          package:
            *package-language-server
          filters:
            branches:
              ignore: /.*/
            tags:
              only: *tag-language-server
          requires:
            - language-server
      # Publish Soql Data Viewer - runs on tag: data-view-vX.X.X ----
      - publish-to-npm:
          name: 'Publish Soql Data Viewer'
          package:
            *package-soql-data-view
          filters:
            branches:
              ignore: /.*/
            tags:
              only: *tag-soql-data-view
          requires:
            - soql-data-view
